version: '3.9'

services:
  mysql:
    platform: linux/x86_64
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - ~/apps/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_PASSWORD=123456
      - MYSQL_USER=userbook
      - MYSQL_DATABASE=bookdb